import img1 from "../../Componentes/CardsReceitas/imgsReceitas/Receita1.webp";
import img2 from "../../Componentes/CardsReceitas/imgsReceitas/Receita2.jpg";
import img3 from "../../Componentes/CardsReceitas/imgsReceitas/Receita3.jpg";
import img4 from "../../Componentes/CardsReceitas/imgsReceitas/Receita4.webp";
import img5 from "../../Componentes/CardsReceitas/imgsReceitas/Receita5.jpg";
import img6 from "../../Componentes/CardsReceitas/imgsReceitas/Receita6.jpg";
import img7 from "../../Componentes/CardsReceitas/imgsReceitas/receita7.jpg";
import img8 from "../../Componentes/CardsReceitas/imgsReceitas/receita8.webp";
import img9 from "../../Componentes/CardsReceitas/imgsReceitas/receita9.jpg";
import img10 from "../../Componentes/CardsReceitas/imgsReceitas/receita10.jpg";
import img11 from "../../Componentes/CardsReceitas/imgsReceitas/receita11.jpg";
import img12 from "../../Componentes/CardsReceitas/imgsReceitas/receita12.jpg";
import img13 from "../../Componentes/CardsReceitas/imgsReceitas/receita13.webp";
import img14 from "../../Componentes/CardsReceitas/imgsReceitas/receita14.webp";
import img15 from "../../Componentes/CardsReceitas/imgsReceitas/Receita15.jpg";

// alteração do conteudo da pagina

export const AlmocoPagina = [
  {
    tipo: "Almoco",
    banner: img1,
    titulo: "Estrogonofe de carne",
    dificuldade: "Fácil",
    tempo: "até 30 minutos",
    rendimento: "4 porções",
    ingreditentes: [
      "500 gramas de alcatra cortada em tirinhas",
      "1/4 xícaras (chá) de manteiga",
      "1 unidade de cebola picada",
      "1 colher (sobremesa) de mostarda",
      "1 colher (sopa) de ketchup",
      "1 pitada de pimenta-do-reino",
      "1 unidade de tomate sem pele picado",
      "1 xicara (chá) de cogumelo variado | variados escorridos",
      "1 lata de creme de leite",
      "sal a gosto",
    ],
    preparo: [
      "1 - Derreta a manteiga e refogue a cebola até ficar transparente.",
      "2 - Junte a carne e tempere o sal.",
      "3 - Mexa até a carne dourar de todos os lados.",
      "4 - Acrescente a mostarda, o ketchup, a pimenta-do-reino e o tomate picado.",
      "5 - Cozinhe até formar um  molho espesso.",
      "6 - Se necessário, adicione água quente aos poucos.",
      "7 - Quando o molho estiver encorpado e a carne macia,adicone os cogumelos e o creme de leite.",
      "8 - Mexa por 1 minuto e retire do fogo.",
      "9 - Sirva imediatamente, acompanhado de arroz e batata palha.",
    ],
    categoria: "Carnes",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Carnes",
    metodo: ["Refogado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Refogado",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Dia a DIa",
    linkFiltroOca: "/receitas/ReceitasFiltradas/DiaDia",
    id: 1,
  },

  {
    tipo: "Almoco",
    banner: img2,
    titulo: "Macarrão de forno com maionese e linguiça",
    dificuldade: "Fácil",
    tempo: "até 30 minutos",
    rendimento: "6 porções",
    ingreditentes: [
      "500 gramas de macarrão fusilli (parafuso)",
      "2 colheres (sopa) de óleo",
      "1 cebola média picada",
      "200 gramas de linguiça calabesa defumada picada",
      "2 tomates sem pele picados",
      "100 gramas de peito de peru picado",
      "½ xícara (chá) de caldo de legumes",
      "½ xícara (chá) de molho de tomate",
      "2 colheres (sopa) de queijo parmesão",
      "150 gramas de queijo mussarela ralada grossa",
      "4 colheres (sopa) de maionese",
      "Sal a gosto",
      "Salsa (ou salsinha) picada a gosto",
    ],
    preparo: [
      "1 - Cozinhe o macarrão na água com sal até ficar al dente. Escorra e reserve.",
      "2 - Em uma fritadeira, aqueça o óleo, doute a cebola e a linguiça.",
      "3 - Misture o tomate , o peito de peru, o caldo de legumes e o molho de tomate.",
      "4 - Cozinhe por 3 minutos e desligue o fogo.",
      "5 - Em um refratário, misture o macarrão, o refogado de linguiça, peito de peru, o parmesão, mussarela, o sal, a salsa e a maionese.",
      "6 - Leve ao forno, preaquecido a 220°C, durante 10 minutos e sirva.",
    ],
    categoria: "Massa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Massa",
    metodo: ["Assado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Assado",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Almoço",
    linkFiltroOca: "/receitas/ReceitasFiltradas/Almoco",
    id: 2,
  },

  {
    tipo: "Almoco",
    banner: img9,
    titulo: "Feijoada",
    dificuldade: "Mediano",
    tempo: "180 minutos",
    rendimento: "10 porções",
    ingreditentes: [
      "500 gramas de macarrão fusilli (parafuso)",
      "200 gramas de carne-seca",
      "600 gramas de feijáo preto",
      "2 folhas de louro secas",
      "250 gramas de costelas suínas",
      "250 gramas de linguiça de paio",
      "150 gramas de bacon defumado",
      "1 cebola picada",
      "4 dentes de alho picados",
      "1 laranja",
    ],
    preparo: [
      "1 - Corte a carne seca em cubos médios e coloque em uma tigela funda.",
      "2 - Cubra com água e deixe de molho por 12 horas, trocando a água de 4 em 4 horas.",
      "3 - Corte o lombo em cubos médios e coloque em uma tigela funda.",
      "4 - Cubra com água e deixe de molho por 12 horas, trocando a água de 4 em 4 horas.",
      "5 - No dia seguinte coloque 2 litros de água para ferver, lave bem o feijão e coloque em um recipiente fundo.",
      "6 - Despeje a água fervendo no feijão e deixe de molho por 20 minutos. Escorra A água e reserve o feijão molhado.",
      "7 - Afervente rapidamente a carne seca dessalgada, o lombo dessalgado e a costelinha de porco. Reserve",
      "8 - Corte o bacon em cubos médios, reservando o courinho se despejar um pouco de gordura.",
      "9 - Leve 2,5 litros de água no fogo até ferver. Em uma panela de pressão, coloque o courinho do bacon e refogue até ele enrolar.",
      "10 - Coloque o feijão que estava de molho, cubra com a água fervendo, adicione as folhas de louro, carne seca, o lombo e a costelinha de porco e leve para cozinhar por 20 minutos a partir do momento que a panela começar a chiar.",
      "11 - Corte o paio e a linguiça calabresa em rodelas. Afervente rapidamente o paio e a linguiça. Reserve",
      "12 - Em uma panela grande coloque a gordura reservada do bancon e leve ao fogo para derreter e refogue a cebola picada, o alho picado, o bacon em cubos, a linguiça calabresa e o paio.",
      "13 - Junte o feijão cozido com as carnes na refogada, lave bem a laranja (inteira e com a casca). Coloque a laranja na panela.",
      "14 - cozinhe tudo em fogo baixo por 20 minutos até que o caldo da feijoada esteja bem cremoso, os feijôes cozidos eas carnes macias.",
      "15 - Se necessário coloque mais água fervente durante o cozimento. Assim que ficar pronta retire a laranja e o courinho do bacon.",
      "16 - Siva acompanhado de couve refogada, vinagre de tomates, gomos de laranja, arroz branco e farofa.",
    ],
    categoria: "Carnes",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Carnes",
    metodo: ["Cozido"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Cozido",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Almoço",
    linkFiltroOca: "/receitas/ReceitasFiltradas/Almoco",
    id: 9,
  },

  {
    tipo: "Almoco",
    banner: img10,
    titulo: "Mac chesse",
    dificuldade: "Fácil",
    tempo: "25 minutos",
    rendimento: "4 porções",
    ingreditentes: [
      "1 pacote de macarrão tipo caracol cozido 'al dente'",
      "1 colher e ½ (sopa) de farinha de trigo",
      "10 fatias de queijo cheddar tipo sanduíche cortado em tiras",
      "pimenta-do-reino",
      "3 colheres (sopa) de manteiga",
      "2 xícaras de leite interal",
      "queijo parmesão",
      "sal",
    ],
    preparo: [
      "1 - Derreta a manteiga e coloque a farinha sem parar de mexer.",
      "2 - Coloque o leite e em seguida o queijo mexendo sempre.",
      "3 - Quando engrossar coloque por cima do macarrão cozido.",
      "4 - Salpique parmessão e leve ao forno até gratinar.",
    ],
    categoria: "Massa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Massa",
    metodo: ["Assado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Assado",
    origem: "Estadonidense",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Estadonidense",
    ocasiao: "Dia a Dia",
    linkFiltroOca: "/receitas/ReceitasFiltradas/DiaDia",
    id: 10,
  },

  {
    tipo: "Almoco",
    banner: img15,
    titulo: "Almôndegas de Frango",
    dificuldade: "Fácil",
    tempo: "15 minutos",
    rendimento: "4 porções",
    ingreditentes: [
      "1kg de peito de frango",
      "½ cebola",
      "1 dente de alho",
      "1 colher (sopa) de azeite",
      "1 colher (sopa) de ervas variadas",
      "1 colher (chá) de páprica",
      "Sal e pimenta a gosto",
    ],
    preparo: [
      "1 - Triture o alho e a cebola, adicione os tomates e triture até estarem bem picados.",
      "2 - Transfira para uma panela de pressão e adicione também o azeite, ervas, sal e pimenta.",
      "3 - Agora triture novamente a cebola com o alho , adicione o frango em pedaços e triture até ficar bem moído e com liga.",
      "4 - transfira para uma tigela e adicione o azeite, ervas, páprica, sal e pimenta.",
      "5 - Misture bem, modele as almôndegas e acomode diretamente sobre o molho na panela.",
      "6 - Misture delicadamente para cobrir as almôndegas com o molho, tampe a panela e cozinhe por 15 minutos.",
      "7 - Quando o tempo terminar retire a pressão, abra, misture e sirva.",
      "8 - Finalize com queijo ralado e ervas.",
    ],
    categoria: "Carnes",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Carnes",
    metodo: ["Cozido"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Cozido",
    origem: "Persa",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Persa",
    ocasiao: "Dia a Dia",
    linkFiltroOca: "/receitas/ReceitasFiltradas/DiaDia",
    id: 15,
  },
];

export const FestaPagina = [
  {
    tipo: "Festa",
    banner: img3,
    titulo: "Pamonha doce",
    dificuldade: "Fácil",
    tempo: "60 minutos",
    rendimento: "4 porções",
    ingreditentes: [
      "400 gramas de grões de milho doce - cerca de 4 espigas",
      "75 ml de leite",
      "150 gramas de açúcar",
      "1 colher (sopa) de manteiga derretida",
      "Sal",
    ],
    preparo: [
      "1 - Corte a ponta da espiga, retire o milho e limpe os fios de seda. Separe as cascas mais bonitas para 'embrulhar' a pamonha",
      "2 - Bata os gãos com o leite, açúcar, manteiga derretida e o sal. A mistura deve ser grossa, se necessário adicione mais leite.",
      "3 - Lave os cascas de milho escale-as em água fervente por alguns segundos - para torná-las mais maleáveis.",
      "4 - Embrulhe as pamonhas na casca de milho. Por fim, amarre o 'pacote'.",
      "5 - Encha uma panela grande com água e deixe ferver. Coloque as pamonhas dentro da panela, cobrindo inteiramente de água.",
      "6 - Tampe e cozinhe por cerca de 45 minutos, até que as cascas fiquem amareladas.",
      "7 - Escorra as pamonhas e sirva.",
      "Dica: Recheie a pamonha com queijo branco ou coalho.",
    ],
    categoria: "Sobremesa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Sobremesa",
    metodo: ["Cozido"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Cozido",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Feriados especiais",
    linkFiltroOca: "/receitas/ReceitasFiltradas/Feriado",
    id: 3,
  },
  {
    tipo: "Festa",
    banner: img4,
    titulo: "Bolo de aipim com coco",
    dificuldade: "Fácil",
    tempo: "60 minutos",
    rendimento: "8 porções",
    ingreditentes: [
      "1 pacote de 100g de coco ralado",
      "3 ovos inteiros",
      "7 gostas de essência de baunilha",
      "1 e ½ xícara (chá) de açúcar",
      "1,5kg de aipim cru ralado",
      "2 xícaras (240 ml) de leite integral",
      "2 colheres (sopa) de manteiga ou margarina",
    ],
    preparo: [
      "1 - Pre-aqueça o forno a 180°C",
      "2 - Misture os ovos com o aipim, numa travessa com uma colher",
      "3 - Acrescente o leite, o açucar, a manteiga, o sal, coco e a essência de baunilha e mexa.",
      "4 - Transfira o conteúdo da travessa para uma forma de furo central untada e enfarinhada.",
      "5 - Coloque no forno e asse por 45 minutos a 180°C.",
      "6 - Retire do forno, desenforme, sirva e aproveite seu maravilhoso bolo de aipim.",
    ],
    categoria: "Bolos",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Bolo",
    metodo: ["Assado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Assado",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Café da tarde",
    linkFiltroOca: "/receitas/ReceitasFiltradas/CafeTarde",
    id: 4,
  },
  {
    tipo: "Festa",
    banner: img7,
    titulo: "Coxinha de frango",
    dificuldade: "Fácil",
    tempo: "15 minutos",
    rendimento: "20 porções",
    ingreditentes: [
      "Massa",
      "4 xícaras (chá) de Batata flocos",
      "2 e 1/2 xícaras (chá) de leite quente",
      "1 colher (sopa) de margarina",
      "1 cubo de caldo de galinha",
      "3 colheres (sopa) de farinha de trigo",
      "1 ovo",
      "Farinha de rosca e 1 clara de ovo",
      "Óleo para fritar",

      "Recheio",
      "120g de frango cozido e desfiado",
      "½ cebola picada",
      "½ tomate picado",
      "½ cubo de caldo de galinha",
      "1 colher (chá) de extrato de tomate",
      "Sal, pimenta e cheiro verde a gosto",
    ],
    preparo: [
      "1 - Refogue o frango com a cebola, tomate e demais temperos.",
      "2 - Adicione margarina, o caldo de galinha e a batata flocos em leite quente.",
      "3 - Acrescente o ovo e a farinha de trigo, amasse bem e forme as coxinhas.",
      "4 - Coloque o recheio ao centro, passe-as na farinha de rosca, no ovo batido e novamente na farinha de rosca.",
      "5 - Frite-as no óleo quente",
      "6 - Pronto, sirva quente e se delicie.",
    ],
    categoria: "Massa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Massa",
    metodo: ["Frito"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Frito",
    origem: "França",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Franca",
    ocasiao: "Café da tarde",
    linkFiltroOca: "/receitas/ReceitasFiltradas/CafeTarde",
    id: 7,
  },
  {
    tipo: "Festa",
    banner: img8,
    titulo: "Massa de pastel",
    dificuldade: "Fácil",
    tempo: "30 minutos",
    rendimento: "8 porções",
    ingreditentes: [
      "1kg de farinha de trigo",
      "1 colher (sopa) sal",
      "1/2 dose de pinga",
      "250 ml de água",
      "1/2 xícaras (chá) de óleo",
      "1 ovo",
      "1 colher (chá) vinagre",
    ],
    preparo: [
      "1 - Misture os ingredientes em uma tigela e amasse com as mãos.",
      "2 - Sove bem a massa sobre uma superfície lisa enfarinhada.",
      "3 - Utilize um rolo para esticar a massa e deixá-la na espessura desejada.",
      "4 - Corte a massa no tamanho que quiser fazer seu pastel.",
      "5 - Recheie de acordo com a sua preferência.",
      "6 - Frite em óleo quente.",
      "7 - Sirva quentinho e saboreie.",
    ],
    categoria: "Massa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Massa",
    metodo: ["Frito"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Frito",
    origem: "Ásia",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Asia",
    ocasiao: "Café da tarde",
    linkFiltroOca: "/receitas/ReceitasFiltradas/CafeTarde",
    id: 8,
  },
];

export const SobremesaPagina = [
  {
    tipo: "Sobremesa",
    banner: img5,
    titulo: "Sobremesa dos Deuses",
    dificuldade: "Fácil",
    tempo: "110 minutos",
    rendimento: "8 porções",
    ingreditentes: [
      "1 pacote de mistura em pó para pudim sabor baunilha",
      "600 ml de leite",
      "1 pote de cream cheese (150g)",
      "2 coelhes (sopa) de açúcar",
      "2 colheres (sopa) de margarina em temperatura ambiente",
      "2 xícaras (chá) de chantily pronto",
      "2/3 de pacote de bolacha sabor chocolate",
    ],
    preparo: [
      "1 - Em uma panela, misture o pó para pudim e o leite, leve ao fogo mexendo sempre até engrossar.",
      "2 - Deixe esfriar e bata com um batedor de arame para ficar homogêneo e reserve.",
      "3 - Na batedeira, acrescente o cream cheese, o açúcar e a margarina. Pare de bater e misture o chantily.",
      "4 - Coloque metade do pudim em um refratário pequeno e arrume as bolachas inteiras ao redor do refratário.",
      "5 - Por cima do pudim, espalhe metade do creme de cream cheese e metade das bolachas trituradas.",
      "6 - Coloque o pudim e o creme de cream cheese restantes e finalize com a outra metade das bolachas trituradas.",
      "7 - Cubra com filme plástico e leve à geladeira por 1 hora. Sirva gelado.",
    ],
    categoria: "Sobremesa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Sobremesa",
    metodo: ["Cozido"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Cozido",
    origem: "Indefinida",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Indefinido",
    ocasiao: "Feriados especiais",
    linkFiltroOca: "/receitas/ReceitasFiltradas/Feriado",
    id: 5,
  },
  {
    tipo: "Sobremesa",
    banner: img6,
    titulo: "Pudim de leite condensado",
    dificuldade: "Fácil",
    tempo: "60 minutos",
    rendimento: "7 porções",
    ingreditentes: [
      "1 caixinha de leite condensado",
      "A mesma medida de leite",
      "1 xícara (chá) de açúcar",
      "3 ovos",
    ],
    preparo: [
      "1 - Em uma panela em fogo médio derreta o açúcar até atingir o ponto de caramelo",
      "2 - Adicione o caramelo em uma forma de 12cm e deixe esfriar",
      "3 - Em uma tigela misture o leite condensado, o leite e os ovos e misture até que fique bem homogêneo.",
      "4 - Adicione e misture na forma com a calda e cubra com papel alumínio.",
      "5 - Leve ao forno dentro de uma forma com 2 dedos de água em banho maria por 1 hora a 180ºC.",
      "6 - Retire e se delicie."
    ],
    categoria: "Sobremesa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Sobremesa",
    metodo: ["Assado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Assado",
    origem: "Portugal",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Portugal",
    ocasiao: "Café da tarde",
    linkFiltroOca: "/receitas/ReceitasFiltradas/CafeTarde",
    id: 6,
  },
  {
    tipo: "Sobremesa",
    banner: img12,
    titulo: "Mosaico de gelatina",
    dificuldade: "Fácil",
    tempo: "240 minutos",
    rendimento: "8 porções",
    ingreditentes: [
      "1 lata de leite condensado",
      "1 caixa de creme de leite",
      "6 caixar de gelatinas de diversos sabores",
    ],
    preparo: [
      "1 - Misture o leite condensado com o creme de leite, prepare as gelatinas separadas e corte em cubos.",
      "2 - Qundo a gelatina estiver endurecida coloque ela dentro do creme",
      "3 - Leve para geladeira e deixe de 3 a 4 horas",
      "4 - Sirva gelado.",
    ],
    categoria: "Sobremesa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Sobremesa",
    metodo: ["Simples"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Simples",
    origem: "Indefinido",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Indefinido",
    ocasiao: "Feriados especiais",
    linkFiltroOca: "/receitas/ReceitasFiltradas/Feriado",
    id: 12,
  },
  {
    tipo: "Sobremesa",
    banner: img13,
    titulo: "Paçoca",
    dificuldade: "Fácil",
    tempo: "45 minutos",
    rendimento: "15 porções",
    ingreditentes: [
      "1 xícara (chá) de açúcar",
      "2 xícaras (chá) de amendoim torrado e sem pele",
      "1 pitada de sal",
    ],
    preparo: [
      "1 - Reúna todos os ingredientes.",
      "2 - Coloque todos os ingredientes em um liquidificador ou processador e bata até formar uma farofa fina.",
      "3 - Se precisar, pare de bate e, com a ajuda de uma colher, misture o excesso que se formou nas laterais dp copo e bolte a bater.",
      "4 - Passe a farofa para uma tigela e mexa nela com as pontas dos dedos até o amendoim soltar o óleo.",
      "5 - Transfira a farofa para um refratário ,espalhe e amasse.",
      "6 - Leve-a para a geladeira e deixe por cerca de 30 minutos",
      "7 - Agora é só cortar e servir.",
    ],
    categoria: "Sobremesa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Sobremesa",
    metodo: ["Simples"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Simples",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Feriados especiais",
    linkFiltroOca: "/receitas/ReceitasFiltradas/Feriado",
    id: 13,
  },
  {
    tipo: "Sobremesa",
    banner: img14,
    titulo: "Rocambole doce",
    dificuldade: "Fácil",
    tempo: "70 minutos",
    rendimento: "10 porções",
    ingreditentes: [
      "6 ovos",
      "5 colheres (sopa) de água",
      "1/2 xícara (chá) de açúcar",
      "1/2 xícara (chá) de farinha de trigo",
      "1 colher (sopa) de fermento em pó",
      "1 lata de leite condesado",
      "Açúcar de confeiteiro para polvilhar",
    ],
    preparo: [
      "1 - Em uma batedeira, bata os ovos com a água até dobrar de volume. Sem parar de bater junte o açúcar aos poucos.",
      "2 - Bata até formar uma mistura clara e fofa. Desligue a batedeira e peneire a farinha de trigo e o fermento em pó.",
      "3 - Despeje em uma assadeira regular forrada com papel-manteiga, e leve ao forno a 180°C, preaquecido, por 20 minutos.",
      "4 - Retire do forno e desenforme ainda quente sobre um papel-manteiga polvilhado com açucar.",
      "5 - Escolha um recheio para adiconar",
    ],
    categoria: "Sobremesa",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Sobremesa",
    metodo: ["Assado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Assado",
    origem: "França",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Franca",
    ocasiao: "Café da tarde",
    linkFiltroOca: "/receitas/ReceitasFiltradas/CafeTarde",
    id: 14,
  },
];

export const LanchePagina = [
  {
    tipo: "Lanche",
    banner: img11,
    titulo: "Pão de queijo",
    dificuldade: "Fácil",
    tempo: "40 minutos",
    rendimento: "12 porções",
    ingreditentes: [
      "3 ovos",
      "1 xícara e 1/2 (chá) de polvilho doce",
      "1 xícara e 1/2 (chá) de polvilho azedo",
      "1 xícara (chá) de leite",
      "150ml de óleo",
      "150g de óleo",
      "Sal a gosto",
      "Queijo prato ou mussarela (opcional)",
    ],
    preparo: [
      "1 - Coloque o forno pré-aquecido a 220°C e unte a forma de cupcakes com manteiga ou margarina e farinha detrigo.",
      "2 - No liquidificador, coloque o óleo, leite, os ovos e bata bem.",
      "3 - Depois, Acrescente os dois tipos de polvilhos no copo do liquidificador e bata novamente , criando uma massa homogênea.",
      "4 - Adicione o queijo parmessão e corrija o sal (cuidado com a quantidade, pois o queijo costuma ser salgado).",
      "5 - Preencha as forminhas de cupcake com a massa e, se desejar, coloque cubinhos de goiabada ou de queijo mussarela.",
      "6 - Coloque para assar no forno por aproximadamente 10 minutos.",
      "7 - Diminuaa temperatura para 180°C e deixe assar por mais 20 minutos ou até que estejam levemente dourados.",
      "8 - Agora é só aproveitar seus deliciosos pães de queijo.",
    ],
    categoria: "Lanche",
    linkFiltroCat: "/receitas/ReceitasFiltradas/Lanches",
    metodo: ["Assado"],
    linkFiltroMet: "/receitas/ReceitasFiltradas/Assado",
    origem: "Brasileira",
    linkFiltroOri: "/receitas/ReceitasFiltradas/Brasileira",
    ocasiao: "Café da tarde",
    linkFiltroOca: "/receitas/ReceitasFiltradas/CafeTarde",
    id: 11,
  },
];
